---
title: "Clone ETFs"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Adrian D. Garcia"
date: "August 2020"
output:
  html_document:
    toc: true
    toc_float: true
---

#Getting Started

```{r setup, message=FALSE, warning=FALSE}

library(tidyverse) #For Data Analysis
library(lubridate) #For working with dates
library(DT) #For visualizing tables

```

## Data

```{r data_upload, message=FALSE}

MFs <- read_csv("~/Data/Clone_ETFs/Mutual_Funds/MS_MFS_081820_Full.csv",
                 guess_max = 25000) %>% 
  mutate(TYPE = "MUTUAL FUND")


ETFs <- read_csv("~/Data/Clone_ETFs/ETFs/MS_ETFS_081820_Full.csv",
                 guess_max = 25000) %>% 
  mutate(TYPE = "ETF")

Data <- full_join(ETFs, MFs) %>% 
  rename_all(make.names)

```

#Working

You can also embed plots, for example:

```{r pressure, echo=FALSE}

Management <- Data %>% 
  group_by(Strategy.Name, Management.Company, TYPE) %>% 
  summarise(COUNT = n()) %>% 
  pivot_wider(names_from = TYPE, values_from = COUNT) %>% 
  group_by(Strategy.Name, Management.Company)

Mgt_Matches <- Management %>%
  filter(!is.na(`MUTUAL FUND`) &
           !is.na(ETF))

Mgt_Matches_df <- Data %>% 
  filter(Strategy.Name %in% Mgt_Matches$Strategy.Name &
           !is.na(Management.Company))

###

Branding <- Data %>% 
  group_by(Strategy.Name, Branding.Name, TYPE) %>% 
  summarise(COUNT = n()) %>% 
  pivot_wider(names_from = TYPE, values_from = COUNT) %>% 
  group_by(Strategy.Name, Branding.Name)

Brand_Matches <- Branding %>%
  filter(!is.na(`MUTUAL FUND`) &
           !is.na(ETF))

Brand_Matches_df <- Data %>% 
  filter(Strategy.Name %in% Brand_Matches$Strategy.Name &
           !is.na(Branding.Name) &
           !is.na(Strategy.Name)) 

###

Firm <- Data %>% 
  group_by(Strategy.Name, Firm.Name, TYPE) %>% 
  summarise(COUNT = n()) %>% 
  pivot_wider(names_from = TYPE, values_from = COUNT) %>% 
  group_by(Strategy.Name, Firm.Name)

Firm_Matches <- Firm %>%
  filter(!is.na(`MUTUAL FUND`) &
           !is.na(ETF))

Firm_Matches_df <- Data %>% 
  filter(Strategy.Name %in% Firm_Matches$Strategy.Name &
           !is.na(Firm.Name) &
           !is.na(Strategy.Name))

test <- full_join(Mgt_Matches_df, Brand_Matches_df) %>% 
  full_join(., Firm_Matches_df)

# df2 <- Data %>% 
#   filter(Strategy.Name %in% Blanks$Strategy.Name) %>% 
#   mutate(Name.Mod = str_replace(Name, "\\s\\w*(™)?$", "")) %>% 
#   select(Name, Name.Mod, TYPE, everything()) %>% 
#   group_by(Strategy.Name, Management.Company)
# 
Blanks <- Data %>%
  group_by(Strategy.Name, Management.Company) %>%
  filter(is.na(Strategy.Name))
# 
# b <- df2 %>% 
#   group_by(Name.Mod, TYPE) %>% 
#   summarise(COUNT = n()) %>% 
#   pivot_wider(names_from = TYPE, values_from = COUNT)

```



```{r name_matches, message=FALSE}

df <- Data %>% 
  mutate(Name.Mod = str_replace(Name, "\\s\\w*(™)?$", "")) %>% 
  select(Name, Name.Mod, TYPE, everything())

names <- df %>% 
  group_by(Name.Mod, TYPE) %>% 
  count() %>% 
  pivot_wider(names_from = TYPE, values_from = n) %>% 
  filter(!is.na(`MUTUAL FUND`)&!is.na(ETF))


```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
